# Generated by Django 4.2.16 on 2024-12-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar el catálogo de vehículo')]},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_de_creación',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_de_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
