# Generated by Django 5.1.2 on 2024-12-03 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar el catálogo de vehículo'), ('can_add_vehiculomodel', 'Puede agregar un modelo de vehículo')]},
        ),
    ]
